version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./app/compose/local/django/Dockerfile
    image: clearpath
    command: /start
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env/.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: clearpath
      POSTGRES_PASSWORD: clearpath
      POSTGRES_DB: clearpath_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
