#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 /app/manage.py collectstatic --noinput
python3 /app/manage.py migrate

/usr/local/bin/gunicorn clearpath_home.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/app